<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Canonical Correlation Analysis | STAT 372 Open Textbook (R)</title>
  <meta name="description" content="This is an open textbook resource for the STAT372 course at MacEwan University, an introduction to Multivariate Statistics and Machine Learning." />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Canonical Correlation Analysis | STAT 372 Open Textbook (R)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an open textbook resource for the STAT372 course at MacEwan University, an introduction to Multivariate Statistics and Machine Learning." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Canonical Correlation Analysis | STAT 372 Open Textbook (R)" />
  
  <meta name="twitter:description" content="This is an open textbook resource for the STAT372 course at MacEwan University, an introduction to Multivariate Statistics and Machine Learning." />
  

<meta name="author" content="Dr. Wanhua Su" />


<meta name="date" content="2025-07-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="clustering-analysis.html"/>
<link rel="next" href="multidimensional-scaling.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preamble</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#learning-outcomes"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#some-examples"><i class="fa fa-check"></i><b>2.2</b> Some Examples</a>
<ul>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#example-1-storm-survival-of-sparrows"><i class="fa fa-check"></i>Example 1: Storm Survival of Sparrows</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#example-2-spam-or-e-mail"><i class="fa fa-check"></i>Example 2: Spam or E-mail?</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#example-3-classification-of-iris"><i class="fa fa-check"></i>Example 3: Classification of Iris</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#multivariate-methods-covered-in-stat-372"><i class="fa fa-check"></i><b>2.3</b> Multivariate Methods Covered in STAT 372</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#review-univariate-analysis"><i class="fa fa-check"></i><b>2.4</b> Review: Univariate Analysis</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="intro.html"><a href="intro.html#random-variable-and-its-distribution"><i class="fa fa-check"></i><b>2.4.1</b> Random Variable and Its Distribution</a></li>
<li class="chapter" data-level="2.4.2" data-path="intro.html"><a href="intro.html#properties-of-expectation-and-variance"><i class="fa fa-check"></i><b>2.4.2</b> Properties of Expectation and Variance</a></li>
<li class="chapter" data-level="2.4.3" data-path="intro.html"><a href="intro.html#continuous-random-variables"><i class="fa fa-check"></i><b>2.4.3</b> Continuous Random Variables</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#revisit-learning-learning-outcomes"><i class="fa fa-check"></i>Revisit Learning Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="matrix-algebra.html"><a href="matrix-algebra.html"><i class="fa fa-check"></i><b>3</b> Matrix Algebra</a>
<ul>
<li class="chapter" data-level="" data-path="matrix-algebra.html"><a href="matrix-algebra.html#learning-outcomes-1"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="3.1" data-path="matrix-algebra.html"><a href="matrix-algebra.html#vectors"><i class="fa fa-check"></i><b>3.1</b> Vectors</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="matrix-algebra.html"><a href="matrix-algebra.html#some-basic-operations-on-vectors"><i class="fa fa-check"></i><b>3.1.1</b> Some Basic Operations on Vectors</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="matrix-algebra.html"><a href="matrix-algebra.html#matrices"><i class="fa fa-check"></i><b>3.2</b> Matrices</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="matrix-algebra.html"><a href="matrix-algebra.html#basic-operations-on-matrix"><i class="fa fa-check"></i><b>3.2.1</b> Basic Operations on Matrix</a></li>
<li class="chapter" data-level="3.2.2" data-path="matrix-algebra.html"><a href="matrix-algebra.html#eigenvalues-and-eigenvectors"><i class="fa fa-check"></i><b>3.2.2</b> Eigenvalues and Eigenvectors</a></li>
<li class="chapter" data-level="3.2.3" data-path="matrix-algebra.html"><a href="matrix-algebra.html#spectral-eigen-decomposition"><i class="fa fa-check"></i><b>3.2.3</b> Spectral (Eigen) Decomposition</a></li>
<li class="chapter" data-level="3.2.4" data-path="matrix-algebra.html"><a href="matrix-algebra.html#singular-value-decomposition"><i class="fa fa-check"></i><b>3.2.4</b> Singular-Value Decomposition</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="matrix-algebra.html"><a href="matrix-algebra.html#mean-vectors-and-covariance-matrices"><i class="fa fa-check"></i><b>3.3</b> Mean Vectors and Covariance Matrices</a></li>
<li class="chapter" data-level="3.4" data-path="matrix-algebra.html"><a href="matrix-algebra.html#sample-mean-vector-and-covariance-matrix"><i class="fa fa-check"></i><b>3.4</b> Sample Mean Vector and Covariance Matrix</a></li>
<li class="chapter" data-level="3.5" data-path="matrix-algebra.html"><a href="matrix-algebra.html#review-exercises"><i class="fa fa-check"></i><b>3.5</b> Review Exercises</a></li>
<li class="chapter" data-level="" data-path="matrix-algebra.html"><a href="matrix-algebra.html#revisit-the-learning-outcomes"><i class="fa fa-check"></i>Revisit the Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html"><i class="fa fa-check"></i><b>4</b> Displaying Multivariate Data and Measures of Distance</a>
<ul>
<li class="chapter" data-level="" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#learning-outcomes-2"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="4.1" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#display-multivariate-data"><i class="fa fa-check"></i><b>4.1</b> Display Multivariate Data</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#scatterplot"><i class="fa fa-check"></i><b>4.1.1</b> Scatterplot</a></li>
<li class="chapter" data-level="4.1.2" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#graphs-of-growth-curves"><i class="fa fa-check"></i><b>4.1.2</b> Graphs of Growth Curves</a></li>
<li class="chapter" data-level="4.1.3" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#star-plots"><i class="fa fa-check"></i><b>4.1.3</b> Star Plots</a></li>
<li class="chapter" data-level="4.1.4" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#chernoff-faces-plot"><i class="fa fa-check"></i><b>4.1.4</b> Chernoff Faces Plot</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#distance-in-multivariate-analysis"><i class="fa fa-check"></i><b>4.2</b> Distance in Multivariate Analysis</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#distances-for-quantitative-variables"><i class="fa fa-check"></i><b>4.2.1</b> Distances for Quantitative Variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#distance-for-categorical-variables"><i class="fa fa-check"></i><b>4.2.2</b> Distance for Categorical Variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#distance-for-mixed-variable-types"><i class="fa fa-check"></i><b>4.2.3</b> Distance for Mixed Variable Types</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#multivariate-normal-distribution"><i class="fa fa-check"></i><b>4.3</b> Multivariate Normal Distribution</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#properties-of-multivariate-normal-distribution"><i class="fa fa-check"></i><b>4.3.1</b> Properties of Multivariate Normal Distribution</a></li>
<li class="chapter" data-level="4.3.2" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#bivariate-normal-distribution"><i class="fa fa-check"></i><b>4.3.2</b> Bivariate Normal Distribution</a></li>
<li class="chapter" data-level="4.3.3" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#contour-of-multivariate-normal-distribution"><i class="fa fa-check"></i><b>4.3.3</b> Contour of Multivariate Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#the-sampling-distribution-of-mathbfbar-x-and-boldsymbols"><i class="fa fa-check"></i><b>4.4</b> The Sampling Distribution of <span class="math inline">\(\mathbf{\bar X}\)</span> and <span class="math inline">\(\boldsymbol{S}\)</span></a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#distributions-related-to-normal-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Distributions Related to Normal Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#applications-to-distributions-related-to-sample-means"><i class="fa fa-check"></i><b>4.4.2</b> Applications to Distributions Related to Sample Means</a></li>
<li class="chapter" data-level="4.4.3" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#generalize-to-multivariate-cases"><i class="fa fa-check"></i><b>4.4.3</b> Generalize to Multivariate Cases</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#review-exercises-1"><i class="fa fa-check"></i><b>4.5</b> Review Exercises</a></li>
<li class="chapter" data-level="" data-path="displaying-multivariate-data-and-measures-of-distance.html"><a href="displaying-multivariate-data-and-measures-of-distance.html#revisit-the-learning-outcomes-1"><i class="fa fa-check"></i>Revisit the Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html"><i class="fa fa-check"></i><b>5</b> Hypothesis Tests on Mean Vectors</a>
<ul>
<li class="chapter" data-level="" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#learning-outcomes-3"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="5.1" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#hypothesis-test-for-one-mean-vector"><i class="fa fa-check"></i><b>5.1</b> Hypothesis Test for one Mean Vector</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#univariate-case"><i class="fa fa-check"></i><b>5.1.1</b> Univariate Case</a></li>
<li class="chapter" data-level="5.1.2" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#multivariate-case"><i class="fa fa-check"></i><b>5.1.2</b> Multivariate Case</a></li>
<li class="chapter" data-level="5.1.3" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#evaluating-multivariate-normality"><i class="fa fa-check"></i><b>5.1.3</b> Evaluating Multivariate Normality</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#hypothesis-test-for-two-mean-vectors"><i class="fa fa-check"></i><b>5.2</b> Hypothesis Test for Two Mean Vectors</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#univariate-case-based-on-two-independent-samples"><i class="fa fa-check"></i><b>5.2.1</b> Univariate Case Based on Two Independent Samples</a></li>
<li class="chapter" data-level="5.2.2" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#multivariate-case-based-on-two-independent-samples"><i class="fa fa-check"></i><b>5.2.2</b> Multivariate Case Based on Two Independent Samples</a></li>
<li class="chapter" data-level="5.2.3" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#two-sample-non-pooled-hotellings-t2-test"><i class="fa fa-check"></i><b>5.2.3</b> Two-sample Non-pooled Hotelling’s <span class="math inline">\(T^2\)</span> Test</a></li>
<li class="chapter" data-level="5.2.4" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#two-sample-hotellings-t2-confidence-interval"><i class="fa fa-check"></i><b>5.2.4</b> Two-sample Hotelling’s <span class="math inline">\(T^2\)</span> Confidence Interval</a></li>
<li class="chapter" data-level="5.2.5" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#univariate-case-based-on-a-paired-sample"><i class="fa fa-check"></i><b>5.2.5</b> Univariate Case Based on a Paired Sample</a></li>
<li class="chapter" data-level="5.2.6" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#multivariate-case-based-on-a-paired-sample"><i class="fa fa-check"></i><b>5.2.6</b> Multivariate Case Based on a Paired Sample</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#hypothesis-test-for-several-mean-vectors"><i class="fa fa-check"></i><b>5.3</b> Hypothesis Test for Several Mean Vectors</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#univariate-case-one-way-anova-f-test"><i class="fa fa-check"></i><b>5.3.1</b> Univariate Case: One-Way ANOVA F Test</a></li>
<li class="chapter" data-level="5.3.2" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#multivariate-case-one-way-manova"><i class="fa fa-check"></i><b>5.3.2</b> Multivariate Case: One-Way MANOVA</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="hypothesis-tests-on-mean-vectors.html"><a href="hypothesis-tests-on-mean-vectors.html#revisit-the-learning-outcomes-2"><i class="fa fa-check"></i>Revisit the Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html"><i class="fa fa-check"></i><b>6</b> Principal Component Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#learning-outcomes-4"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="6.1" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#finding-the-principal-components"><i class="fa fa-check"></i><b>6.1</b> Finding the Principal Components</a></li>
<li class="chapter" data-level="6.2" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#scaling-in-principal-component-analysis"><i class="fa fa-check"></i><b>6.2</b> Scaling in Principal Component Analysis</a></li>
<li class="chapter" data-level="6.3" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#limitations-of-principal-component-analysis"><i class="fa fa-check"></i><b>6.3</b> Limitations of Principal Component Analysis</a></li>
<li class="chapter" data-level="6.4" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#further-reading"><i class="fa fa-check"></i><b>6.4</b> Further Reading</a></li>
<li class="chapter" data-level="" data-path="principal-component-analysis.html"><a href="principal-component-analysis.html#revisit-the-learning-outcomes-3"><i class="fa fa-check"></i>Revisit the Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>7</b> Factor Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="factor-analysis.html"><a href="factor-analysis.html#learning-outcomes-5"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="7.1" data-path="factor-analysis.html"><a href="factor-analysis.html#model-of-factor-analysis"><i class="fa fa-check"></i><b>7.1</b> Model of Factor Analysis</a></li>
<li class="chapter" data-level="7.2" data-path="factor-analysis.html"><a href="factor-analysis.html#estimating-factor-loadings-l_ij-and-specific-variance-psi_i"><i class="fa fa-check"></i><b>7.2</b> Estimating Factor Loadings <span class="math inline">\(l_{ij}\)</span> and Specific Variance <span class="math inline">\(\psi_i\)</span></a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="factor-analysis.html"><a href="factor-analysis.html#the-principle-component-method"><i class="fa fa-check"></i><b>7.2.1</b> The Principle Component Method</a></li>
<li class="chapter" data-level="7.2.2" data-path="factor-analysis.html"><a href="factor-analysis.html#the-maximum-likelihood-method"><i class="fa fa-check"></i><b>7.2.2</b> The Maximum Likelihood Method</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="factor-analysis.html"><a href="factor-analysis.html#factor-rotation"><i class="fa fa-check"></i><b>7.3</b> Factor Rotation</a></li>
<li class="chapter" data-level="7.4" data-path="factor-analysis.html"><a href="factor-analysis.html#factor-scores"><i class="fa fa-check"></i><b>7.4</b> Factor Scores</a></li>
<li class="chapter" data-level="" data-path="factor-analysis.html"><a href="factor-analysis.html#revisit-the-learning-outcomes-4"><i class="fa fa-check"></i>Revisit the Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html"><i class="fa fa-check"></i><b>8</b> Discriminant Analysis and Classification</a>
<ul>
<li class="chapter" data-level="" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#learning-outcomes-6"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="8.1" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#introduction-1"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#performance-measure"><i class="fa fa-check"></i><b>8.2</b> Performance Measure</a></li>
<li class="chapter" data-level="8.3" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#overfitting-and-cross-validation"><i class="fa fa-check"></i><b>8.3</b> Overfitting and Cross Validation</a></li>
<li class="chapter" data-level="8.4" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#classification-models"><i class="fa fa-check"></i><b>8.4</b> Classification Models</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#k-nearest-neighbors"><i class="fa fa-check"></i><b>8.4.1</b> <span class="math inline">\(K\)</span> Nearest Neighbors</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#logistic-regression-for-binary-response"><i class="fa fa-check"></i><b>8.5</b> Logistic Regression for Binary Response</a>
<ul>
<li class="chapter" data-level="" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#interpretation-of-beta_i"><i class="fa fa-check"></i>Interpretation of <span class="math inline">\(\beta_i\)</span></a></li>
<li class="chapter" data-level="" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#estimation-of-beta_i"><i class="fa fa-check"></i>Estimation of <span class="math inline">\(\beta_i\)</span></a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#logistic-regression-for-multi-class-nominal-data"><i class="fa fa-check"></i><b>8.6</b> Logistic Regression for Multi-class Nominal Data</a></li>
<li class="chapter" data-level="8.7" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#cumulative-logit-model-for-multi-class-ordinal-data"><i class="fa fa-check"></i><b>8.7</b> Cumulative Logit Model for Multi-class Ordinal Data</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#cumulative-logit-models-with-proportional-odds"><i class="fa fa-check"></i><b>8.7.1</b> Cumulative Logit Models with Proportional Odds</a></li>
<li class="chapter" data-level="8.7.2" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#model-probability-of-each-category"><i class="fa fa-check"></i><b>8.7.2</b> Model Probability of Each Category</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#model-selection-for-logistic-regression"><i class="fa fa-check"></i><b>8.8</b> Model Selection for Logistic Regression</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#aic-and-bic"><i class="fa fa-check"></i><b>8.8.1</b> AIC and BIC</a></li>
<li class="chapter" data-level="8.8.2" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#forward-selection"><i class="fa fa-check"></i><b>8.8.2</b> Forward Selection</a></li>
<li class="chapter" data-level="8.8.3" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#backward-elimination"><i class="fa fa-check"></i><b>8.8.3</b> Backward Elimination</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#model-checking"><i class="fa fa-check"></i><b>8.9</b> Model Checking</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#residual-analysis"><i class="fa fa-check"></i><b>8.9.1</b> Residual Analysis</a></li>
<li class="chapter" data-level="8.9.2" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#preditive-power-accuracy-and-roc-curve"><i class="fa fa-check"></i><b>8.9.2</b> Preditive Power: Accuracy and ROC Curve</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#classification-tree-recursive-partitioning"><i class="fa fa-check"></i><b>8.10</b> Classification Tree (Recursive Partitioning)</a></li>
<li class="chapter" data-level="8.11" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#regression-tree"><i class="fa fa-check"></i><b>8.11</b> Regression Tree</a></li>
<li class="chapter" data-level="8.12" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#random-forest"><i class="fa fa-check"></i><b>8.12</b> Random Forest</a></li>
<li class="chapter" data-level="8.13" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#support-vector-machines"><i class="fa fa-check"></i><b>8.13</b> Support Vector Machines</a></li>
<li class="chapter" data-level="8.14" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#neural-networks"><i class="fa fa-check"></i><b>8.14</b> Neural Networks</a></li>
<li class="chapter" data-level="8.15" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#classical-methods"><i class="fa fa-check"></i><b>8.15</b> Classical Methods</a>
<ul>
<li class="chapter" data-level="8.15.1" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#mahalanobis-distance-method"><i class="fa fa-check"></i><b>8.15.1</b> Mahalanobis Distance Method</a></li>
<li class="chapter" data-level="8.15.2" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#bayes-posterior"><i class="fa fa-check"></i><b>8.15.2</b> Bayes Posterior</a></li>
<li class="chapter" data-level="8.15.3" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#fishers-discriminant-analysis"><i class="fa fa-check"></i><b>8.15.3</b> Fisher’s Discriminant Analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.16" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#summary"><i class="fa fa-check"></i><b>8.16</b> Summary</a></li>
<li class="chapter" data-level="" data-path="discriminant-analysis-and-classification.html"><a href="discriminant-analysis-and-classification.html#revisit-learning-outcomes"><i class="fa fa-check"></i>Revisit Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="clustering-analysis.html"><a href="clustering-analysis.html"><i class="fa fa-check"></i><b>9</b> Clustering Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="clustering-analysis.html"><a href="clustering-analysis.html#learning-outcomes-7"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="9.1" data-path="clustering-analysis.html"><a href="clustering-analysis.html#introduction-2"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="clustering-analysis.html"><a href="clustering-analysis.html#clustering-methods"><i class="fa fa-check"></i><b>9.2</b> Clustering Methods</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="clustering-analysis.html"><a href="clustering-analysis.html#hierarchical-method"><i class="fa fa-check"></i><b>9.2.1</b> Hierarchical Method</a></li>
<li class="chapter" data-level="9.2.2" data-path="clustering-analysis.html"><a href="clustering-analysis.html#k-means"><i class="fa fa-check"></i><b>9.2.2</b> K-Means</a></li>
<li class="chapter" data-level="9.2.3" data-path="clustering-analysis.html"><a href="clustering-analysis.html#model-based-clustering"><i class="fa fa-check"></i><b>9.2.3</b> Model-Based Clustering</a></li>
<li class="chapter" data-level="9.2.4" data-path="clustering-analysis.html"><a href="clustering-analysis.html#pros-and-cons-of-clustering-methods"><i class="fa fa-check"></i><b>9.2.4</b> Pros and Cons of Clustering Methods</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="clustering-analysis.html"><a href="clustering-analysis.html#determine-k-number-of-clusters"><i class="fa fa-check"></i><b>9.3</b> Determine <span class="math inline">\(K\)</span>: Number of Clusters</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="clustering-analysis.html"><a href="clustering-analysis.html#the-elbow-plot-method"><i class="fa fa-check"></i><b>9.3.1</b> The Elbow Plot Method</a></li>
<li class="chapter" data-level="9.3.2" data-path="clustering-analysis.html"><a href="clustering-analysis.html#the-silhouette-score"><i class="fa fa-check"></i><b>9.3.2</b> The Silhouette Score</a></li>
<li class="chapter" data-level="9.3.3" data-path="clustering-analysis.html"><a href="clustering-analysis.html#gap-statistics"><i class="fa fa-check"></i><b>9.3.3</b> Gap Statistics</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="clustering-analysis.html"><a href="clustering-analysis.html#side-note-on-the-em-algorithm"><i class="fa fa-check"></i>Side-Note on the EM Algorithm</a></li>
<li class="chapter" data-level="" data-path="clustering-analysis.html"><a href="clustering-analysis.html#revisit-learning-outcomes-1"><i class="fa fa-check"></i>Revisit Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="canonical-correlation-analysis.html"><a href="canonical-correlation-analysis.html"><i class="fa fa-check"></i><b>10</b> Canonical Correlation Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="canonical-correlation-analysis.html"><a href="canonical-correlation-analysis.html#learning-outcomes-8"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="10.1" data-path="canonical-correlation-analysis.html"><a href="canonical-correlation-analysis.html#objective"><i class="fa fa-check"></i><b>10.1</b> Objective</a></li>
<li class="chapter" data-level="10.2" data-path="canonical-correlation-analysis.html"><a href="canonical-correlation-analysis.html#obtain-the-canonical-variates-pairs"><i class="fa fa-check"></i><b>10.2</b> Obtain the Canonical Variates Pairs</a></li>
<li class="chapter" data-level="10.3" data-path="canonical-correlation-analysis.html"><a href="canonical-correlation-analysis.html#interpretation"><i class="fa fa-check"></i><b>10.3</b> Interpretation</a></li>
<li class="chapter" data-level="10.4" data-path="canonical-correlation-analysis.html"><a href="canonical-correlation-analysis.html#testing-mathbfsigma_120"><i class="fa fa-check"></i><b>10.4</b> Testing <span class="math inline">\(\mathbf{\Sigma}_{12}=0\)</span></a></li>
<li class="chapter" data-level="" data-path="canonical-correlation-analysis.html"><a href="canonical-correlation-analysis.html#revisit-learning-outcomes-2"><i class="fa fa-check"></i>Revisit Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html"><i class="fa fa-check"></i><b>11</b> Multidimensional Scaling</a>
<ul>
<li class="chapter" data-level="" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html#learning-outcomes-9"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="11.1" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html#objective-1"><i class="fa fa-check"></i><b>11.1</b> Objective</a></li>
<li class="chapter" data-level="11.2" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html#methods"><i class="fa fa-check"></i><b>11.2</b> Methods</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html#classical-scaling"><i class="fa fa-check"></i><b>11.2.1</b> Classical Scaling</a></li>
<li class="chapter" data-level="11.2.2" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html#metric-scaling"><i class="fa fa-check"></i><b>11.2.2</b> Metric Scaling</a></li>
<li class="chapter" data-level="11.2.3" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html#non-metric-scaling"><i class="fa fa-check"></i><b>11.2.3</b> Non-metric Scaling</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html#example"><i class="fa fa-check"></i><b>11.3</b> Example</a></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling.html"><a href="multidimensional-scaling.html#revisit-learning-outcomes-3"><i class="fa fa-check"></i>Revisit Learning Outcomes</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT 372 Open Textbook (R)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="canonical-correlation-analysis" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">10</span> Canonical Correlation Analysis<a href="canonical-correlation-analysis.html#canonical-correlation-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="learning-outcomes-8" class="section level2 unnumbered hasAnchor">
<h2>Learning Outcomes<a href="canonical-correlation-analysis.html#learning-outcomes-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>After finishing this chapter, students should be able to</p>
<ul>
<li>Understand the objective of canonical correlation analysis.</li>
<li>Prove important results related to canonical correlation analysis.</li>
<li>Conduct a canonical correlation analysis in R.</li>
<li>Interpret the computer output of a canonical correlation analysis.</li>
<li>Conduct a hypothesis test to test whether the canonical relations are significant.</li>
<li>Determine the proper number of canonical variates pairs.</li>
</ul>
</div>
<div id="objective" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Objective<a href="canonical-correlation-analysis.html#objective" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Consider two sets of variables,
<span class="math display">\[
\mathbf{X}=
\left[
\begin{array}{c}
X_1\\ X_2\\ \vdots\\ X_p
\end{array}
\right],
\quad \quad
\mathbf{Y}=
\left[
\begin{array}{c}
Y_1\\ Y_2\\ \vdots\\ Y_q
\end{array}
\right]
\quad \quad
p\le q
\]</span>
with
<span class="math display">\[
\text{cov}\left[
\begin{array}{c}
\mathbf{X}\\ \cdots\\\mathbf{Y}
\end{array}
\right]=\text{cov}\left[
\begin{array}{c}
X_1\\ X_2\\ \vdots\\ X_p\\ \cdots \\ Y_1\\ Y_2\\ \vdots\\ Y_q
\end{array}
\right]=\left[
\begin{array}{ccc}
\text{var}(\mathbf{X}) &amp;\vdots &amp;\text{cov}(\mathbf{X},\mathbf{Y})   \\
\cdots&amp;\cdots&amp;\cdots\\
\text{cov}(\mathbf{Y},\mathbf{X})   &amp;\vdots &amp;  \text{var}(\mathbf{Y})\\
\end{array}
\right]=\left[
\begin{array}{ccc}
\mathbf{\Sigma}_{11} &amp;\vdots &amp;\mathbf{\Sigma}_{12}   \\
\cdots&amp;\cdots&amp;\cdots\\
\mathbf{\Sigma}_{21}  &amp;\vdots &amp;  \mathbf{\Sigma}_{22} \\
\end{array}
\right]
\]</span></p>
<p>We want to use <span class="math inline">\(k\)</span> uncorrelated canonical variates pairs <span class="math inline">\((u_i, v_i), i=1, 2 \cdots, k\)</span> to represent the data such that the pair <span class="math inline">\((u_i, v_i)\)</span> has the <span class="math inline">\(i\)</span>th largest correlation. That is,
<span class="math display">\[\begin{align*}
u_1&amp;=\mathbf{a}_1^{T}\mathbf{X}=a_{11}X_1+a_{12}X_2+\cdots+a_{1p}X_p\\
u_2&amp;=\mathbf{a}_2^{T}\mathbf{X}=a_{21}X_1+a_{22}X_2+\cdots+a_{2p}X_p\\
\vdots\\
u_p&amp;=\mathbf{a}_p^{T}\mathbf{X}=a_{p1}X_1+a_{p2}X_2+\cdots+a_{pp}X_p\\
v_1&amp;=\mathbf{b}_1^{T}\mathbf{Y}=b_{11}Y_1+b_{12}Y_2+\cdots+b_{1q}Y_q\\
v_2&amp;=\mathbf{b}_2^{T}\mathbf{Y}=b_{21}Y_1+b_{22}Y_2+\cdots+b_{2q}Y_q\\
\vdots\\
v_q&amp;=\mathbf{b}_q^{T}\mathbf{Y}=b_{q1}Y_1+b_{q2}Y_2+\cdots+b_{qq}Y_q\\
\end{align*}\]</span>
with
<span class="math display">\[
\text{cov}(u_1, v_1)\ge \text{cov}(u_2, v_2)\ge \cdots \ge \text{cov}(u_p, v_p).
\]</span>
And the canonical variates pairs <span class="math inline">\((u_i, v_i)\)</span> are uncorrelated, that is
<span class="math display">\[
\text{cov}(u_i, u_j)=0, \text{cov}(u_i, v_j)=0, \text{cov}(v_i, v_j)=0, \text{cov}(u_j, v_i)=0, \mbox{ for $i&lt;j$}.
\]</span>
The correlations of the canonical variates pairs <span class="math inline">\(\rho_i=\text{Corr}(u_i, v_i)\)</span> are called the canonical correlations. Canonical correlation analysis allows us to summarize the covariance matrix <span class="math inline">\(\mathbf{\Sigma}_{12}\)</span> whose dimension is <span class="math inline">\(p\times q\)</span> using <span class="math inline">\(p\)</span> canonical correlations <span class="math inline">\(\rho_i, i=1, 2, \cdots, p\)</span>.</p>
</div>
<div id="obtain-the-canonical-variates-pairs" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Obtain the Canonical Variates Pairs<a href="canonical-correlation-analysis.html#obtain-the-canonical-variates-pairs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It can be shown that the first canonical variates pair is associated to the eigenvector corresponding to the largest eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span>, the correlation of the first canonical pair is the square root of the largest eigenvalue. In general, the <span class="math inline">\(i\)</span>th canonical variates pair is associated to the eigenvector corresponding to the <span class="math inline">\(i\)</span>th largest eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span>.</p>
<p><span class="math inline">\(\textbf{Proof}\)</span>: We want to maximize <span class="math inline">\(\text{cov}(u, v)=\text{cov}(\mathbf{a}^T\mathbf{X},\mathbf{b}^T\mathbf{Y})=\mathbf{a}^T\mathbf{\Sigma}_{12}\mathbf{b}\)</span> with the constraints <span class="math inline">\(\mathbf{a}^T\mathbf{\Sigma}_{11}\mathbf{a}=1\)</span> and <span class="math inline">\(\mathbf{b}^T\mathbf{\Sigma}_{22}\mathbf{b}=1\)</span>.</p>
<p><span class="math display">\[
\rho = \text{corr}(u,v) = \frac{\text{cov}(u,v)}{\sqrt{\text{Var}(u) \text{Var}(v)}} = \frac{\vec{a}^{\top} \Sigma_{12} \vec{b}}{\sqrt{(\vec{a}^{\top} \Sigma_{11} \vec{a})(\vec{b}^{\top} \Sigma_{22} \vec{b})}}
\]</span></p>
<p><span class="math inline">\(\text{Want to maximize }\)</span> <span class="math inline">\(\rho\)</span></p>
<p><span class="math inline">\(\text{Maximize }\)</span> <span class="math inline">\(\vec{a}^{\top} \Sigma_{12} \vec{b} \quad \text{s.t.}\)</span>
<span class="math inline">\(\vec{a}^{\top} \Sigma_{11} \vec{a} = 1, \quad \vec{b}^{\top} \Sigma_{22} \vec{b} = 1\)</span></p>
<p><span class="math inline">\(\text{The objective function is}\)</span>
<span class="math display">\[
Q(\vec{a},\vec{b}, \lambda, \gamma) = \vec{a}^{\top} \Sigma_{12} \vec{b} - \frac{\lambda}{2}(\vec{a}^{\top} \Sigma_{11} \vec{a} - 1) - \frac{\gamma}{2}(\vec{b}^{\top} \Sigma_{22} \vec{b} - 1)
\]</span></p>
<p><span class="math display">\[
Q(\vec{a},\vec{b}, \lambda, \gamma) = \vec{a}^{\top} \Sigma_{12} \vec{b} - \frac{\lambda}{2}(\vec{a}^{\top} \Sigma_{11} \vec{a} - 1) - \frac{\gamma}{2}(\vec{b}^{\top} \Sigma_{22} \vec{b} - 1)
\]</span>
<span class="math display">\[
\frac{\partial Q}{\partial \vec{a}} \quad \text{(px1)} = \Sigma_{12} \vec{b} - \frac{\lambda}{2}(\Sigma_{11} \vec{a} + (\vec{a}^{\top} \Sigma_{11})^{\top}) \\
= \Sigma_{12} \vec{b} - \frac{\lambda}{2}(\Sigma_{11} \vec{a} + \Sigma_{11}^{\top} \vec{a}) \quad \Sigma_{11} = \Sigma_{11}^{\top} \\
= \Sigma_{12} \vec{b} - \lambda \Sigma_{11} \vec{a} = 0 \\
\implies \Sigma_{12} \vec{b} = \lambda \Sigma_{11} \vec{a} \quad \text{(1)}
\]</span></p>
<p><span class="math display">\[
\frac{\partial Q}{\partial \vec{b}} \quad \text{qx1} = (\vec{a}^{\top} \Sigma_{12})^{\top} - 0 - \frac{\gamma}{2}(\Sigma_{22} \vec{b} + (\vec{b}^{\top} \Sigma_{22})^{\top}) \\
= \Sigma_{12}^{\top} \vec{a} - \frac{\gamma}{2}(\Sigma_{22} \vec{b} + \Sigma_{22}^{\top} \vec{b}) \quad \Sigma_{22}^{\top} = \Sigma_{22} \\
= \Sigma_{21} \vec{a} - \gamma \Sigma_{22} \vec{b} = 0 \\
\implies \Sigma_{21} \vec{a} = \gamma \Sigma_{22} \vec{b} \quad \text{(2)} \implies \vec{b} = \Sigma_{22}^{-1} \frac{\Sigma_{21}}{\gamma} \vec{a}
\]</span></p>
<p><span class="math display">\[
\frac{\partial Q}{\partial \lambda} = -\frac{1}{2}(\vec{a}^{\top} \Sigma_{11} \vec{a} - 1) = 0 \implies \vec{a}^{\top} \Sigma_{11} \vec{a} = 1
\]</span></p>
<p><span class="math display">\[
\frac{\partial Q}{\partial \gamma} = -\frac{1}{2}(\vec{b}^{\top} \Sigma_{22} \vec{b} - 1) = 0 \implies \vec{b}^{\top} \Sigma_{22} \vec{b} = 1
\]</span></p>
<p><span class="math display">\[
\vec{a}^{\top} \times \text{(1)} \quad \quad \quad  = \vec{a}^{\top} \Sigma_{12} \vec{b} = \lambda \vec{a}^{\top} \Sigma_{11} \vec{a} = \lambda \cdot 1 = \lambda
\]</span></p>
<p><span class="math display">\[
\vec{b}^{\top} \times \text{(2)} \quad \quad \quad  = \vec{b}^{\top} \Sigma_{21} \vec{a} = \gamma \vec{b}^{\top} \Sigma_{22} \vec{b} = \gamma \cdot 1 = \gamma
\]</span>
<span class="math display">\[
\implies \lambda = \gamma
\]</span></p>
<p><span class="math display">\[\text{From (2)} \implies \vec{b} = \Sigma_{22}^{-1} \Sigma_{21} \vec{a} / \gamma \]</span>
<span class="math display">\[
\vec{b} = \frac{1}{\gamma} \Sigma_{22}^{-1} \Sigma_{21} \vec{a} \quad \text{(3)}
\]</span>
<span class="math inline">\(\text{Plug (3) back to (1)}\)</span>
<span class="math display">\[
\Sigma_{12} \vec{b} = \lambda \Sigma_{11} \vec{a} \\
\implies \Sigma_{12} \frac{1}{\gamma} \Sigma_{22}^{-1} \Sigma_{21} \vec{a} = \lambda \Sigma_{11} \vec{a} \\
\Sigma_{12} \Sigma_{22}^{-1} \Sigma_{21} \vec{a} = \lambda \gamma \Sigma_{11} \vec{a} \\
\Sigma_{11}^{-1} \Sigma_{12} \Sigma_{22}^{-1} \Sigma_{21} \vec{a} = \lambda^2 \vec{a}
\]</span>
<span class="math inline">\(\lambda^2 \text{ is an eigenvalue of } \Sigma_{11}^{-1} \Sigma_{12} \Sigma_{22}^{-1} \Sigma_{21}\)</span>
<span class="math inline">\(\text{and }\)</span> <span class="math inline">\(\vec{a} \text{ is the corresponding eigenvector.}\)</span>
<span class="math inline">\(\text{where }\)</span> <span class="math inline">\(A\vec{a}=\lambda\vec{a}\)</span></p>
<p><span class="math inline">\(\lambda = \vec{a}^{\top} \Sigma_{11} \vec{b}\)</span>
<span class="math inline">\(\text{to maximize }\)</span> <span class="math inline">\(\vec{a}^{\top} \Sigma_{11} \vec{b} \text{ is to maximize } \lambda \text{ (or } \lambda^2)\)</span></p>
<p><span class="math inline">\(\vec{a} \text{ is related to the eigenvector}\)</span>
<span class="math inline">\(\text{associated to the largest eigenvalue}\)</span>
<span class="math inline">\(\text{of }\)</span> <span class="math inline">\(\Sigma_{11}^{-1} \Sigma_{12} \Sigma_{22}^{-1} \Sigma_{21}\)</span></p>
<p>The steps to obtain the canonical variates pairs are as follows.</p>
<ol style="list-style-type: decimal">
<li>Find the eigenvalues of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span>, <span class="math inline">\(\lambda_1^2 \ge \lambda_2^2 \ge \cdots \ge \lambda_p^2\)</span>. Obtain the corresponding unit eigenvectors <span class="math inline">\(\mathbf{e}_1, \mathbf{e}_2, \cdots, \mathbf{e}_p\)</span>.</li>
<li>The <span class="math inline">\(i\)</span>th canonical variates pair <span class="math inline">\((u_i, v_i)\)</span> is given by
<span class="math display">\[
u_i=\mathbf{a}_i^T\mathbf{X}; \quad \mathbf{a}_i=\frac{\mathbf{e}_i}{\sqrt{c_i}}; \mbox{ with $c_i=\mathbf{e}_i^T \mathbf{\Sigma}_{11} \mathbf{e}_i$}
\]</span>
<span class="math display">\[
v_i=\mathbf{b}_i^T\mathbf{Y}; \quad \mathbf{b}_i=\frac{1}{\lambda_i}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{a}_i
\]</span>
And the correlation of <span class="math inline">\(u_i\)</span> and <span class="math inline">\(v_i\)</span> is
<span class="math display">\[
\rho_i=\frac{\text{cov}(u_i, v_i)}{\sqrt{\text{var}(u_i)\text{var}(v_i)}}=\frac{\mathbf{a}_i^T \mathbf{\Sigma}_{12}\mathbf{b}_i}{\sqrt{(\mathbf{a}_i^T \mathbf{\Sigma}_{11}\mathbf{a}_i)(\mathbf{b}_i^T \mathbf{\Sigma}_{22}\mathbf{b}_i)}}=\lambda_i
\]</span></li>
</ol>
<p><span class="math inline">\(\textbf{Note}\)</span>:If we want to find <span class="math inline">\(q\)</span> canonical variates to represent <span class="math inline">\(\mathbf{Y}\)</span>, we can find the eigenvalues of the matrix <span class="math inline">\(\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\)</span>, <span class="math inline">\(\lambda_1^2 \ge \lambda_2^2 \ge \cdots \ge \lambda_p^2\ge \cdots \ge \lambda_q^2\)</span>. The first <span class="math inline">\(p\)</span> eigenvalues are the same as those of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span>. Obtain the corresponding unit eigenvectors <span class="math inline">\(\mathbf{f}_1, \mathbf{f}_2, \cdots, \mathbf{f}_q\)</span>. Then
<span class="math display">\[
\mathbf{b}_i=\frac{\mathbf{f}_i}{\sqrt{d_i}}; \mbox{ with $d_i=\mathbf{f}_i^T \mathbf{\Sigma}_{22} \mathbf{f}_i$}, i=1, 2, \cdots, q
\]</span></p>
<p><span class="math inline">\(\textbf{Proof}\)</span>:The first canonical variates pair is the one giving the largest correlation. That is to maximize
<span class="math display">\[
\rho=\frac{\text{cov}(u, v)}{\sqrt{\text{var}(u)\text{var}(v)}}=\frac{\mathbf{a}^T \mathbf{\Sigma}_{12}\mathbf{b}}{\sqrt{(\mathbf{a}^T \mathbf{\Sigma}_{11}\mathbf{a})(\mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b})}}.
\]</span>
This is equivalent to maximizing <span class="math inline">\(\mathbf{a}^T \mathbf{\Sigma}_{12}\mathbf{b}\)</span> with the constraints <span class="math inline">\(\mathbf{a}^T \mathbf{\Sigma}_{11}\mathbf{a}=1\)</span> and <span class="math inline">\(\mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b}=1\)</span>. Using the Lagrange multiplier method, we want to find
<span class="math display">\[
\arg \max_{\mathbf{a},\mathbf{b}, \lambda, \gamma} Q=\mathbf{a}^T \mathbf{\Sigma}_{12}\mathbf{b}-\frac{\lambda}{2}(\mathbf{a}^T \mathbf{\Sigma}_{11}\mathbf{a}-1)-\frac{\gamma}{2}(\mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b}-1)
\]</span></p>
<p><span class="math display" id="eq:eq1">\[\begin{align}

\frac{\partial Q}{\partial \mathbf{a}}&amp;=\mathbf{\Sigma}_{12}\mathbf{b}-\lambda \mathbf{\Sigma}_{11}\mathbf{a}=0 \Longrightarrow \mathbf{a}^T\mathbf{\Sigma}_{12}\mathbf{b}=\lambda \mathbf{a}^T\mathbf{\Sigma}_{11}\mathbf{a}=\lambda \\
\tag{10.1}
\end{align}\]</span></p>
<p><span class="math display" id="eq:eq2">\[\begin{align}
\frac{\partial Q}{\partial \mathbf{b}}&amp;=\mathbf{\Sigma}_{21}\mathbf{a}-\gamma \mathbf{\Sigma}_{22}\mathbf{b}=0 \Longrightarrow \mathbf{b}^T\mathbf{\Sigma}_{21}\mathbf{a}=\gamma \mathbf{b}^T\mathbf{\Sigma}_{22}\mathbf{b}=\gamma
\tag{10.2}
\end{align}\]</span>
<span class="math display">\[\begin{align}
\\
\frac{\partial Q}{\partial \lambda}&amp;=0\Longrightarrow  \mathbf{a}^T \mathbf{\Sigma}_{11}\mathbf{a}=1\nonumber\\
\frac{\partial Q}{\partial \gamma}&amp;=0\Longrightarrow \mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b}=1\nonumber
\end{align}\]</span>
Equations (<a href="canonical-correlation-analysis.html#eq:eq1">(10.1)</a>) and (<a href="canonical-correlation-analysis.html#eq:eq2">(10.2)</a>) imply <span class="math inline">\(\lambda=\gamma\)</span>. Equation (<a href="canonical-correlation-analysis.html#eq:eq2">(10.2)</a>) also implies <span class="math inline">\(\mathbf{b}=\frac{1}{\gamma}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{a}\)</span>. Plug it in back to Equation (<a href="canonical-correlation-analysis.html#eq:eq1">(10.1)</a>),
we have
<span class="math display">\[
\mathbf{\Sigma}_{12}\frac{1}{\gamma}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{a}=\lambda \mathbf{\Sigma}_{11} \mathbf{a} \Longrightarrow \mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{a}=\lambda^2\mathbf{a}.
\]</span>
This implies <span class="math inline">\(\lambda^2\)</span> is an eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span> and <span class="math inline">\(\mathbf{a}\)</span> is the corresponding eigenvector. By Equation (<a href="canonical-correlation-analysis.html#eq:eq1">(10.1)</a>), <span class="math inline">\(\mathbf{a}^T\mathbf{\Sigma}_{12}\mathbf{b}=\lambda\)</span>; therefore, to maximize <span class="math inline">\(\mathbf{a}^T\mathbf{\Sigma}_{12}\mathbf{b}\)</span> is to maximize <span class="math inline">\(\lambda\)</span> (or <span class="math inline">\(\lambda^2\)</span>), i.e., the largest eigenvalue. As a result, <span class="math inline">\(\mathbf{a}\)</span> is an eigenvector associated with the largest eigenvalue <span class="math inline">\(\lambda^2\)</span> of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span>. We need to scale <span class="math inline">\(\mathbf{a}\)</span> such that <span class="math inline">\(\mathbf{a}^T \mathbf{\Sigma}_{11}\mathbf{a}=1\)</span>. Suppose <span class="math inline">\(\mathbf{e}\)</span> is the unit eigenvector associated to the largest eigenvalue <span class="math inline">\(\lambda^2\)</span>, let
<span class="math display">\[
\mathbf{a}=\frac{\mathbf{e}}{\sqrt{c}}, \quad \mbox{where $c=\mathbf{e}^T \mathbf{\Sigma}_{11}\mathbf{e}$}.
\]</span>
Let
<span class="math display">\[
\mathbf{b}=\frac{1}{\lambda}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{a}
\]</span>
It can be shown that <span class="math inline">\(\mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b}=1\)</span>,
<span class="math display">\[
\mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b}=(\frac{1}{\lambda}\mathbf{a}^T\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1})\mathbf{\Sigma}_{22}(\frac{1}{\lambda}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{a})=\frac{1}{\lambda^2}\mathbf{a}^T\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{a}=\frac{1}{\lambda^2}\mathbf{a}^T\mathbf{\Sigma}_{11}(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{a})=\frac{1}{\lambda^2}\mathbf{a}^T\mathbf{\Sigma}_{11}(\lambda^2 \mathbf{a})=1
\]</span></p>
<p>Applying the similar idea, we can prove that the second canonical variates pair is related to the eigenvector of the second largest eigenvalue, and etc. If we work on the correlation matrix, the conclusions still hold, just replace the covariance matrices with correlation matrices.</p>
<p><span class="math inline">\(\textbf{Note}\)</span>: There is another way to calculate the canonical variates pairs, the steps are as follows.</p>
<ol style="list-style-type: decimal">
<li>Find the eigenvalues of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\)</span> and the corresponding unit eigenvectors <span class="math inline">\(\mathbf{e}_1, \mathbf{e}_2, \cdots \mathbf{e}_p\)</span>. It can be shown that <span class="math inline">\(\lambda_1^2 \ge \lambda_2^2 \ge \cdots \ge \lambda_p^2\)</span> are also the <span class="math inline">\(p\)</span> largest eigenvalues of the matrix <span class="math inline">\(\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\)</span> with the corresponding unit eigenvectors <span class="math inline">\(\mathbf{f}_1, \mathbf{f}_2, \cdots \mathbf{f}_p\)</span>.</li>
<li>The <span class="math inline">\(i\)</span>th canonical variates pair <span class="math inline">\((u_i, v_i)\)</span> is given by
<span class="math display">\[
u_i=\mathbf{a}_i^T\mathbf{X}; \quad \mathbf{a}_i=\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_i; \quad \quad v_i=\mathbf{b}_i^T\mathbf{Y}; \quad \mathbf{b}_i=\mathbf{\Sigma}_{22}^{-1/2}\mathbf{f}_i
\]</span>
And the correlation of <span class="math inline">\(u_i\)</span> and <span class="math inline">\(v_i\)</span> is <span class="math inline">\(\rho_i=\frac{\text{cov}(u_i, v_i)}{\sqrt{\text{var}(u_i)\text{var}(v_i)}}=\lambda_i\)</span>.</li>
</ol>
<p><span class="math inline">\(\textbf{Proof}\)</span>: Recall that we want to find <span class="math inline">\(\mathbf{a}\)</span> and <span class="math inline">\(\mathbf{b}\)</span> such that
<span class="math display">\[
\rho=\frac{\text{cov}(u, v)}{\sqrt{\text{var}(u)\text{var}(v)}}=\frac{\mathbf{a}^T \mathbf{\Sigma}_{12}\mathbf{b}}{\sqrt{(\mathbf{a}^T \mathbf{\Sigma}_{11}\mathbf{a})(\mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b})}}.
\]</span>
is maximized. Let
<span class="math display">\[
\mathbf{c}=\mathbf{\Sigma}_{11}^{1/2}\mathbf{a}; \mathbf{d}=\mathbf{\Sigma}_{22}^{1/2}\mathbf{b},
\]</span>
then
<span class="math display">\[
\rho=\text{corr}(u,v)=\frac{\text{cov}(u, v)}{\sqrt{\text{var}(u)\text{var}(v)}}=\frac{\mathbf{a}^T \mathbf{\Sigma}_{12}\mathbf{b}}{\sqrt{(\mathbf{a}^T \mathbf{\Sigma}_{11}\mathbf{a})(\mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b})}}=\frac{\mathbf{c}^T\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\mathbf{d}}{\sqrt{(\mathbf{c}^T\mathbf{c})(\mathbf{d}^T\mathbf{d})}}.
\]</span>
By Cauchy Schwarz inequality, the numerator
<span class="math display">\[
\mathbf{c}^T\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\mathbf{d}\le (\mathbf{c}^T\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{c})^{1/2}(\mathbf{d}^T\mathbf{d})^{1/2}.
\]</span></p>
<p>Since <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\)</span> is a <span class="math inline">\(p\times p\)</span> symmetric matrix, we have
<span class="math display">\[
\mathbf{c}^T\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{c}\le \lambda_1\mathbf{c}^T\mathbf{c}
\]</span>
where <span class="math inline">\(\lambda_1\)</span> is the largest eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\)</span> and maximum is attained when <span class="math inline">\(\mathbf{c}=\mathbf{e}_1\)</span>, the unit eigenvector associated with <span class="math inline">\(\lambda_1\)</span>. Therefore, <span class="math inline">\(\mathbf{a}=\mathbf{\Sigma}_{11}^{-1/2} \mathbf{c}=\mathbf{\Sigma}_{11}^{-1/2} \mathbf{e}_1\)</span> and <span class="math inline">\(\mathbf{b} \propto \mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1\)</span>, the <span class="math inline">\(\max_{\mathbf{a}, \mathbf{b}}\text{corr}(\mathbf{a}^T\mathbf{X},\mathbf{b}^T\mathbf{Y})=\sqrt{\lambda_1}\)</span>. Take <span class="math inline">\(\mathbf{b}=\mathbf{\Sigma}_{22}^{-1/2}\mathbf{f}_1\)</span> where <span class="math inline">\(\mathbf{f}_1=\frac{\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1}{|\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1|}=\frac{\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1}{\sqrt{\lambda_1}}\)</span>, the normalized form of <span class="math inline">\(\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1\)</span>.</p>
<p>It can be shown that <span class="math inline">\(\mathbf{f}_1\)</span> is the unit eigenvector corresponding to the largest eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\)</span>. Since <span class="math inline">\(\mathbf{e}_1\)</span> is the unit eigenvector corresponding to the largest eigenvalue of <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\)</span>, we have</p>
<p><span class="math display" id="eq:eq3">\[\begin{align}
\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1=\lambda_1 \mathbf{e}_1
\tag{10.3}
\end{align}\]</span></p>
<p>multiplying equation (<a href="canonical-correlation-analysis.html#eq:eq3">(10.3)</a>) both sides by <span class="math inline">\(\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\)</span>, we have
<span class="math display">\[
\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\underbrace{(\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1)}\limits_{\mbox{eigenvector}}=\lambda_1 \underbrace{(\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1)}\limits_{\mbox{eigenvector}},
\]</span>
which means <span class="math inline">\(\lambda_1\)</span> is also the largest eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\)</span> and the corresponding unit eigenvector is
<span class="math display">\[
\mathbf{f}_1=\frac{\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1}{|\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1|}
=\frac{\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1}{\sqrt{\mathbf{e}_1^T \underbrace{\mathbf{\Sigma}_{11}^{-1/2} \mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1}\limits_{\lambda_1\mathbf{e}_1 \mbox{  by Equation (\@ref(eq:eq1)}}}}=\frac{\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}_1}{\sqrt{\lambda_1}}.
\]</span>
Another way, an easier way to show that <span class="math inline">\(\mathbf{b}=\mathbf{\Sigma}_{22}^{-1/2}\mathbf{f}\)</span> where <span class="math inline">\(\mathbf{f}\)</span> is the unit eigenvector corresponding to the largest eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{22}^{-1/2}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1/2}\)</span> is
<span class="math display">\[
\rho=\frac{\text{cov}(u, v)}{\sqrt{\text{var}(u)\text{var}(v)}}=\frac{\text{cov}(v, u)}{\sqrt{\text{var}(v)\text{var}(u)}}\frac{\mathbf{b}^T \mathbf{\Sigma}_{21}\mathbf{a}}{\sqrt{(\mathbf{b}^T \mathbf{\Sigma}_{22}\mathbf{b})(\mathbf{a}^T \mathbf{\Sigma}_{11}\mathbf{a})}}.
\]</span>
We will arrive at the conclusion by the same logic as we did for <span class="math inline">\(\mathbf{a}\)</span> using Cauchy Schwarz inequality.</p>
<p><span class="math inline">\(\textbf{Result}\)</span></p>
<p>It can be shown that if <span class="math inline">\(\lambda\)</span> is an eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1/2}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\mathbf{\Sigma}_{11}^{-1/2}\)</span> with the corresponding unit eigenvectors <span class="math inline">\(\mathbf{e}\)</span>, then <span class="math inline">\(\lambda\)</span> is also an eigenvalue of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span> with the corresponding eigenvector <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1/2}\mathbf{e}\)</span>.</p>
<div style="page-break-after: always;"></div>
<p><span class="math inline">\(\textbf{Example}\)</span>: Canonical Correlation Analysis</p>
<p>A researcher has collected data on three psychological variables, four academic variables (standardized test scores) for 600 college freshman. She is interested in how the set of psychological variables relates to the academic variables. In particular, the researcher is interested in how many dimensions (canonical variables) are necessary to understand the association between the two sets of variables.The psychological variables are locus-of-control (<span class="math inline">\(X_1\)</span>), self-concept (<span class="math inline">\(X_2\)</span>)and motivation (<span class="math inline">\(X_3\)</span>). The academic variables are standardized tests in reading (<span class="math inline">\(Y_1\)</span>, read), writing (<span class="math inline">\(Y_2\)</span>, write), math (<span class="math inline">\(Y_3\)</span>, math) and science (<span class="math inline">\(Y_4\)</span>, science). Determine the sample canonical variates and their correlations.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="canonical-correlation-analysis.html#cb1-1" tabindex="-1"></a>data0 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/mmreg.csv&quot;</span>)</span>
<span id="cb1-2"><a href="canonical-correlation-analysis.html#cb1-2" tabindex="-1"></a><span class="fu">head</span>(data0)</span></code></pre></div>
<pre><code>##   locus_of_control self_concept motivation read write math science female
## 1            -0.84        -0.24       1.00 54.8  64.5 44.5    52.6      1
## 2            -0.38        -0.47       0.67 62.7  43.7 44.7    52.6      1
## 3             0.89         0.59       0.67 60.6  56.7 70.5    58.0      0
## 4             0.71         0.28       0.67 62.7  56.7 54.7    58.0      0
## 5            -0.64         0.03       1.00 41.6  46.3 38.4    36.3      1
## 6             1.11         0.90       0.33 62.7  64.5 61.4    58.0      1</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="canonical-correlation-analysis.html#cb3-1" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> data0[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb3-2"><a href="canonical-correlation-analysis.html#cb3-2" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> data0[,<span class="dv">4</span><span class="sc">:</span><span class="dv">7</span>]</span>
<span id="cb3-3"><a href="canonical-correlation-analysis.html#cb3-3" tabindex="-1"></a></span>
<span id="cb3-4"><a href="canonical-correlation-analysis.html#cb3-4" tabindex="-1"></a>s11 <span class="ot">&lt;-</span> <span class="fu">cov</span>(x1)</span>
<span id="cb3-5"><a href="canonical-correlation-analysis.html#cb3-5" tabindex="-1"></a>s22 <span class="ot">&lt;-</span> <span class="fu">cov</span>(x2)</span>
<span id="cb3-6"><a href="canonical-correlation-analysis.html#cb3-6" tabindex="-1"></a>s12 <span class="ot">&lt;-</span> <span class="fu">cov</span>(x1,x2)</span>
<span id="cb3-7"><a href="canonical-correlation-analysis.html#cb3-7" tabindex="-1"></a>s21 <span class="ot">&lt;-</span> <span class="fu">t</span>(s12)</span>
<span id="cb3-8"><a href="canonical-correlation-analysis.html#cb3-8" tabindex="-1"></a></span>
<span id="cb3-9"><a href="canonical-correlation-analysis.html#cb3-9" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">solve</span>(s11)<span class="sc">%*%</span>s12<span class="sc">%*%</span><span class="fu">solve</span>(s22)<span class="sc">%*%</span>s21</span>
<span id="cb3-10"><a href="canonical-correlation-analysis.html#cb3-10" tabindex="-1"></a>objA <span class="ot">&lt;-</span> <span class="fu">eigen</span>(A)</span>
<span id="cb3-11"><a href="canonical-correlation-analysis.html#cb3-11" tabindex="-1"></a>ea <span class="ot">&lt;-</span> objA<span class="sc">$</span>vector</span>
<span id="cb3-12"><a href="canonical-correlation-analysis.html#cb3-12" tabindex="-1"></a>(rsuqre <span class="ot">&lt;-</span> objA<span class="sc">$</span>values)</span></code></pre></div>
<pre><code>## [1] 0.1993055329 0.0235189905 0.0005064066</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="canonical-correlation-analysis.html#cb5-1" tabindex="-1"></a>(r <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(objA<span class="sc">$</span>values)) <span class="co">#the correlation</span></span></code></pre></div>
<pre><code>## [1] 0.44643648 0.15335902 0.02250348</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="canonical-correlation-analysis.html#cb7-1" tabindex="-1"></a>ca <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">t</span>(ea)<span class="sc">%*%</span>s11<span class="sc">%*%</span>ea) <span class="co">#figure out the normalizing constants, var(u1)=1</span></span>
<span id="cb7-2"><a href="canonical-correlation-analysis.html#cb7-2" tabindex="-1"></a>(a <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">t</span>(ea)<span class="sc">/</span><span class="fu">sqrt</span>(ca)))<span class="co">#normally, make the one with the largest magnitude positive</span></span></code></pre></div>
<pre><code>##            [,1]       [,2]       [,3]
## [1,] -1.2501212  0.7659633 -0.4966529
## [2,]  0.2367331  0.8421110  1.2051225
## [3,] -1.2491434 -2.6359625  1.0935085</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="canonical-correlation-analysis.html#cb9-1" tabindex="-1"></a>(a <span class="ot">&lt;-</span> <span class="sc">-</span>a)</span></code></pre></div>
<pre><code>##            [,1]       [,2]       [,3]
## [1,]  1.2501212 -0.7659633  0.4966529
## [2,] -0.2367331 -0.8421110 -1.2051225
## [3,]  1.2491434  2.6359625 -1.0935085</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="canonical-correlation-analysis.html#cb11-1" tabindex="-1"></a>(b0 <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">t</span>(<span class="fu">solve</span>(s22)<span class="sc">%*%</span>s21<span class="sc">%*%</span>a)<span class="sc">/</span>r)) <span class="co">#if want p variates</span></span></code></pre></div>
<pre><code>##                 [,1]        [,2]        [,3]
## read     0.044047131  0.00159291 -0.08833171
## write    0.055088843  0.09041460  0.09612884
## math     0.019401098  0.00295546 -0.08782244
## science -0.003797762 -0.12420898  0.08849519</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="canonical-correlation-analysis.html#cb13-1" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">solve</span>(s22)<span class="sc">%*%</span>s21<span class="sc">%*%</span><span class="fu">solve</span>(s11)<span class="sc">%*%</span>s12</span>
<span id="cb13-2"><a href="canonical-correlation-analysis.html#cb13-2" tabindex="-1"></a>objB <span class="ot">&lt;-</span> <span class="fu">eigen</span>(B)</span>
<span id="cb13-3"><a href="canonical-correlation-analysis.html#cb13-3" tabindex="-1"></a>eb <span class="ot">&lt;-</span> objB<span class="sc">$</span>vector</span>
<span id="cb13-4"><a href="canonical-correlation-analysis.html#cb13-4" tabindex="-1"></a>cb <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">t</span>(eb)<span class="sc">%*%</span>s22<span class="sc">%*%</span>eb) <span class="co">#figure out the normalizing constants, var(v1)=1</span></span>
<span id="cb13-5"><a href="canonical-correlation-analysis.html#cb13-5" tabindex="-1"></a>(b <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">t</span>(eb)<span class="sc">/</span><span class="fu">sqrt</span>(cb)))</span></code></pre></div>
<pre><code>##              [,1]        [,2]        [,3]          [,4]
## [1,]  0.044047131  0.00159291  0.08833171  0.1213682652
## [2,]  0.055088843  0.09041460 -0.09612884 -0.0003655481
## [3,]  0.019401098  0.00295546  0.08782244 -0.1342383587
## [4,] -0.003797762 -0.12420898 -0.08849519 -0.0096911430</code></pre>
<p>Since <span class="math inline">\(p=3, q=4\)</span>, we can obtain <span class="math inline">\(\min\{p, q\}=3\)</span> canonical variates pairs. Based on the comupter outputs,
<span class="math display">\[
u_1=1.2501X_1-0.2367X_2+1.2491X_3, \quad v_1=0.0440Y_1+0.0551Y_2+0.0194Y_3-0.0038Y_4
\]</span>
<span class="math inline">\(u_1\)</span> is more related to locus-of-control and motivation since their coefficients are larger in magnitude.<span class="math inline">\(v_1\)</span> is contributed by reading, writing and math. And their correlation is <span class="math inline">\(\rho_1=\text{corr}(u_1, v_1)=0.4464\)</span>.</p>
<p>Similarly, the second and third pairs are
<span class="math display">\[
u_2=-0.7660X_1-0.8421X_2+2.6360X_3, \quad v_2=0.0016Y_1+0.0904Y_2+0.0030Y_3-0.1242Y_4
\]</span>
<span class="math inline">\(u_2\)</span> is more related to motivation and <span class="math inline">\(v_2\)</span> is more related to science. Their correlation is <span class="math inline">\(\rho_2=\corr(u_2, v_2)=0.1534\)</span>.
<span class="math display">\[
u_3=-0.4967X_1-1.2051X_2-1.0935X_3, \quad v_3=-0.0883Y_1+0.0961Y_2-0.0878Y_3+0.0885Y_4
\]</span>
<span class="math inline">\(u_3\)</span> is more related to self-concept and motivation, <span class="math inline">\(v_3\)</span> is quite uniformly contributed by reading, writing, math and science. Their correlation is <span class="math inline">\(\rho_3=\corr(u_3, v_3)=0.0225\)</span>.</p>
<p>We can also obtain the canonical correlations and the canonical variate pairs using the built-in R function.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="canonical-correlation-analysis.html#cb15-1" tabindex="-1"></a><span class="fu">library</span>(CCA)</span>
<span id="cb15-2"><a href="canonical-correlation-analysis.html#cb15-2" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">cc</span>(x1,x2)</span>
<span id="cb15-3"><a href="canonical-correlation-analysis.html#cb15-3" tabindex="-1"></a>m1<span class="sc">$</span>cor <span class="co"># canonical correlations</span></span></code></pre></div>
<pre><code>## [1] 0.44643648 0.15335902 0.02250348</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="canonical-correlation-analysis.html#cb17-1" tabindex="-1"></a>m1<span class="sc">$</span>xcoef <span class="co"># the same as a, coefficients of U</span></span></code></pre></div>
<pre><code>##                        [,1]       [,2]       [,3]
## locus_of_control -1.2501212  0.7659633  0.4966529
## self_concept      0.2367331  0.8421110 -1.2051225
## motivation       -1.2491434 -2.6359625 -1.0935085</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="canonical-correlation-analysis.html#cb19-1" tabindex="-1"></a>m1<span class="sc">$</span>ycoef <span class="co"># the same as b, coefficients of V</span></span></code></pre></div>
<pre><code>##                 [,1]        [,2]        [,3]
## read    -0.044047131 -0.00159291 -0.08833171
## write   -0.055088843 -0.09041460  0.09612884
## math    -0.019401098 -0.00295546 -0.08782244
## science  0.003797762  0.12420898  0.08849519</code></pre>
</div>
<div id="interpretation" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Interpretation<a href="canonical-correlation-analysis.html#interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Even though we can investigate the association between the original variables and their corresponding canonical variates by comparing the magnitudes of the coefficients, it is better to look at the correlations between the original variables and the canonical variates. Now consider regressing <span class="math inline">\(X_i\)</span>s on <span class="math inline">\(u_i\)</span>s,
<span class="math display">\[\begin{align*}
X_1&amp;=c_{11}u_1+c_{12}u_2+\cdots+c_{1p}u_p\\
X_2&amp;=c_{21}u_1+c_{22}u_2+\cdots+c_{2p}u_p\\
\vdots\\
X_p&amp;=c_{p1}u_1+c_{p2}u_2+\cdots+c_{pp}u_p
\end{align*}\]</span>
which means <span class="math inline">\(\mathbf{X}=\mathbf{C}\mathbf{u}\)</span>. Recall that the linear combinations in <span class="math inline">\(\mathbf{X}\)</span> are <span class="math inline">\(\mathbf{u}=\mathbf{A}\mathbf{X}\)</span> where
<span class="math display">\[
\mathbf{A}=\left[
\begin{array}{cccc}
a_{11} &amp;a_{12}&amp;\cdots&amp; a_{1p}\\
a_{21} &amp;a_{22}&amp;\cdots&amp; a_{2p}\\
\vdots&amp;\vdots&amp;\vdots&amp;\vdots\\
a_{p1} &amp;a_{p2}&amp;\cdots&amp; a_{pp}
\end{array}
\right].
\]</span>
Therefore, <span class="math inline">\(\mathbf{C}=\mathbf{A}^{-1}\)</span>, i.e., <span class="math inline">\(\mathbf{X}=\mathbf{A}^{-1}\mathbf{u}\)</span>. Similarly, <span class="math inline">\(\mathbf{Y}=\mathbf{B}^{-1}\mathbf{v}\)</span> where
<span class="math display">\[
\mathbf{B}=\left[
\begin{array}{cccc}
b_{11} &amp;b_{12}&amp;\cdots&amp; b_{1q}\\
b_{21} &amp;b_{22}&amp;\cdots&amp; b_{2q}\\
\vdots&amp;\vdots&amp;\vdots&amp;\vdots\\
b_{q1} &amp;b_{q2}&amp;\cdots&amp; b_{qq}
\end{array}
\right].
\]</span></p>
<p>We would like to explore the correlations between original variable <span class="math inline">\(\mathbf{X}\)</span> and <span class="math inline">\(\mathbf{u}\)</span>, <span class="math inline">\(\mathbf{Y}\)</span> and <span class="math inline">\(\mathbf{u}\)</span>, <span class="math inline">\(\mathbf{X}\)</span> and <span class="math inline">\(\mathbf{v}\)</span>, and <span class="math inline">\(\mathbf{X}\)</span> and <span class="math inline">\(\mathbf{v}\)</span>. Since
<span class="math display">\[
\mathbf{u}=\mathbf{AX}\Longrightarrow \mathbf{X}=\mathbf{A}^{-1}\mathbf{u}; \quad
\mathbf{v}=\mathbf{BY}\Longrightarrow \mathbf{Y}=\mathbf{B}^{-1}\mathbf{v}
\]</span></p>
<p>Then,
<span class="math display">\[\begin{align*}
\text{Corr}(\mathbf{X}, \mathbf{u})&amp;=\text{Corr}(\mathbf{A}^{-1}\mathbf{u}, \mathbf{u})=\mathbf{A}^{-1}\text{Corr}(\mathbf{u}, \mathbf{u})=\mathbf{A}^{-1}\mathbf{I};\\
\text{Corr}(\mathbf{Y}, \mathbf{v})&amp;=\text{Corr}(\mathbf{B}^{-1}\mathbf{v}, \mathbf{v})=\mathbf{B}^{-1}\text{Corr}(\mathbf{v}, \mathbf{v})=\mathbf{B}^{-1}\mathbf{I};\\
\text{Corr}(\mathbf{X}, \mathbf{v})&amp;=\text{Corr}(\mathbf{A}^{-1}\mathbf{u}, \mathbf{v})=\mathbf{A}^{-1}\text{Corr}(\mathbf{u}, \mathbf{v})=\mathbf{A}^{-1}\mathbf{\Lambda};\\
\text{Corr}(\mathbf{Y}, \mathbf{u})&amp;=\text{Corr}(\mathbf{B}^{-1}\mathbf{v}, \mathbf{u})=\mathbf{B}^{-1}\text{Corr}(\mathbf{v}, \mathbf{u})=\mathbf{B}^{-1}\mathbf{\Lambda},
\end{align*}\]</span>
where <span class="math inline">\(\mathbf{\Lambda}\)</span> is a diagonal matrix with <span class="math inline">\(\lambda_1\ge \lambda_2 \ge \cdots \ge \lambda_p\)</span> as the diagonal elements and <span class="math inline">\(\lambda_i^2\)</span> are the eigenvalues of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span>. Take the correlation between <span class="math inline">\(\mathbf{X}\)</span> and <span class="math inline">\(\mathbf{u}\)</span> for example,
<span class="math display">\[
\mathbf{A}^{-1}=\left[
\begin{array}{cccc}
r_{X_1, u_1} &amp;r_{X_1, u_2}&amp;\cdots&amp; r_{X_1,u_p}\\
r_{X_2, u_1} &amp;r_{X_2, u_2}&amp;\cdots&amp; r_{X_2,u_p}\\
\vdots&amp;\vdots&amp;\vdots&amp;\vdots\\
r_{X_p, u_1} &amp;r_{X_p, u_2}&amp;\cdots&amp; r_{X_p,u_p}
\end{array}
\right].
\]</span>
The sum of squares of the first row of <span class="math inline">\(\mathbf{A}^{-1}\)</span> is <span class="math inline">\(\text{Var}(X_1)=0.44927511\)</span>. The sum of squares of all elements in <span class="math inline">\(\mathbf{A}^{-1}\)</span> is the total variation in <span class="math inline">\(\mathbf{X}\)</span> is given by
<span class="math display">\[
\text{Var}(X_1)+\text{Var}(X_2)+\text{Var}(X_3)=\text{trace}(\mathbf{\Sigma_{11}})=0.449+0.498+0.117=1.064.
\]</span></p>
<p>Recall that in linear regression model, the <span class="math inline">\(R^2\)</span> is the percentage of variation in the response variable explained by the predictor variables. Therefore, the sum of squares of the <span class="math inline">\(j\)</span>th column of <span class="math inline">\(\mathbf{A}^{-1}\)</span> divided by the sum of squares of entire matrix of <span class="math inline">\(\mathbf{A}^{-1}\)</span> gives the proportion of variation in <span class="math inline">\(\mathbf{X}\)</span> explained by <span class="math inline">\(u_j\)</span>. Similarly, the sum of squares of the <span class="math inline">\(j\)</span>th column of <span class="math inline">\(\mathbf{B}^{-1}\)</span> divided by the sum of squares of entire matrix of <span class="math inline">\(\mathbf{B}^{-1}\)</span> gives the proportion of variation in <span class="math inline">\(\mathbf{Y}\)</span> explained by <span class="math inline">\(v_j\)</span>.</p>
<p>If we work on the correlation matrix, i.e., the standardized variables, the total variation in the standardized <span class="math inline">\(\mathbf{X}\)</span> is <span class="math inline">\(p\)</span> and the total variation in the standardized <span class="math inline">\(\mathbf{Y}\)</span> is <span class="math inline">\(q\)</span>. Then, the sum of squares of the <span class="math inline">\(j\)</span>th column of <span class="math inline">\(\mathbf{A}^{-1}\)</span> divided by <span class="math inline">\(p\)</span> gives the proportion of variation in <span class="math inline">\(\mathbf{X}\)</span> explained by <span class="math inline">\(u_j\)</span>. Similarly, the sum of squares of the <span class="math inline">\(j\)</span>th column of <span class="math inline">\(\mathbf{B}^{-1}\)</span> divided by <span class="math inline">\(q\)</span> gives the proportion of variation in <span class="math inline">\(\mathbf{Y}\)</span> explained by <span class="math inline">\(v_j\)</span>.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="canonical-correlation-analysis.html#cb21-1" tabindex="-1"></a>(rxu <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(a)))</span></code></pre></div>
<pre><code>##            [,1]       [,2]        [,3]
## [1,] 0.61282695 -0.2638611  0.06399669
## [2,] 0.07052849 -0.2972383 -0.63594265
## [3,] 0.20060823  0.2077361 -0.18456833</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="canonical-correlation-analysis.html#cb23-1" tabindex="-1"></a>(ryv <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(b)))</span></code></pre></div>
<pre><code>##          [,1]      [,2]      [,3]       [,4]
## [1,] 8.894992 -2.474325  2.758692  3.0359049
## [2,] 8.852313  2.149250 -3.305016 -0.8355134
## [3,] 7.531705 -1.769342  2.669746 -4.6532327
## [4,] 6.737088 -6.560291 -2.306895 -0.6799760</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="canonical-correlation-analysis.html#cb25-1" tabindex="-1"></a>(var_x <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(rxu<span class="sc">^</span><span class="dv">2</span>)) <span class="co">#should be diagonal element of s11</span></span></code></pre></div>
<pre><code>## [1] 0.4492751 0.4977479 0.1174634</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="canonical-correlation-analysis.html#cb27-1" tabindex="-1"></a>(<span class="fu">diag</span>(s11))</span></code></pre></div>
<pre><code>## locus_of_control     self_concept       motivation 
##        0.4492751        0.4977479        0.1174634</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="canonical-correlation-analysis.html#cb29-1" tabindex="-1"></a>(var_y <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(ryv<span class="sc">^</span><span class="dv">2</span>)) <span class="co">#should be diagonal element of s22</span></span></code></pre></div>
<pre><code>## [1] 102.07026  94.60393  88.63726  94.20991</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="canonical-correlation-analysis.html#cb31-1" tabindex="-1"></a>(<span class="fu">diag</span>(s22))</span></code></pre></div>
<pre><code>##      read     write      math   science 
## 102.07026  94.60393  88.63726  94.20991</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="canonical-correlation-analysis.html#cb33-1" tabindex="-1"></a><span class="fu">sum</span>(rxu[,<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">sum</span>(rxu<span class="sc">^</span><span class="dv">2</span>) <span class="co">#variation in x explained by u1</span></span></code></pre></div>
<pre><code>## [1] 0.3952843</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="canonical-correlation-analysis.html#cb35-1" tabindex="-1"></a><span class="fu">sum</span>(ryv[,<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">sum</span>(ryv<span class="sc">^</span><span class="dv">2</span>) <span class="co">#variation in y explained by v1</span></span></code></pre></div>
<pre><code>## [1] 0.6840175</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="canonical-correlation-analysis.html#cb37-1" tabindex="-1"></a>(rxv <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(a))<span class="sc">%*%</span><span class="fu">diag</span>(<span class="fu">sqrt</span>(objA<span class="sc">$</span>values)))</span></code></pre></div>
<pre><code>##            [,1]        [,2]         [,3]
## [1,] 0.27358831 -0.04046547  0.001440148
## [2,] 0.03148649 -0.04558417 -0.014310922
## [3,] 0.08955883  0.03185820 -0.004153430</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="canonical-correlation-analysis.html#cb39-1" tabindex="-1"></a>(ryu <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(b))<span class="sc">%*%</span><span class="fu">diag</span>(<span class="fu">sqrt</span>(objB<span class="sc">$</span>values)))</span></code></pre></div>
<pre><code>##          [,1]       [,2]        [,3]          [,4]
## [1,] 3.971049 -0.3794601  0.06208017  8.986796e-09
## [2,] 3.951995  0.3296068 -0.07437436 -2.473262e-09
## [3,] 3.362428 -0.2713445  0.06007856 -1.377436e-08
## [4,] 3.007682 -1.0060798 -0.05191315 -2.012845e-09</code></pre>
<p>Based on the computer output, <span class="math inline">\(u_1\)</span> accounts for 39.53% variation in <span class="math inline">\(\mathbf{X}\)</span> and <span class="math inline">\(v_1\)</span> accounts for 68.40% variation in <span class="math inline">\(\mathbf{Y}\)</span>.</p>
<p>If we work on the standardized variables, i.e., we work on the correlation matrix rather than the covariance matrix, we will identical canonical correlations and canonical variates, but different matrices of correlations between the original variables and canonical variates.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="canonical-correlation-analysis.html#cb41-1" tabindex="-1"></a><span class="co">#if we work on the correlation matrix</span></span>
<span id="cb41-2"><a href="canonical-correlation-analysis.html#cb41-2" tabindex="-1"></a>s11 <span class="ot">&lt;-</span> <span class="fu">cor</span>(x1)</span>
<span id="cb41-3"><a href="canonical-correlation-analysis.html#cb41-3" tabindex="-1"></a>s22 <span class="ot">&lt;-</span> <span class="fu">cor</span>(x2)</span>
<span id="cb41-4"><a href="canonical-correlation-analysis.html#cb41-4" tabindex="-1"></a>s12 <span class="ot">&lt;-</span> <span class="fu">cor</span>(x1,x2)</span>
<span id="cb41-5"><a href="canonical-correlation-analysis.html#cb41-5" tabindex="-1"></a>s21 <span class="ot">&lt;-</span> <span class="fu">t</span>(s12)</span>
<span id="cb41-6"><a href="canonical-correlation-analysis.html#cb41-6" tabindex="-1"></a></span>
<span id="cb41-7"><a href="canonical-correlation-analysis.html#cb41-7" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">solve</span>(s11)<span class="sc">%*%</span>s12<span class="sc">%*%</span><span class="fu">solve</span>(s22)<span class="sc">%*%</span>s21</span>
<span id="cb41-8"><a href="canonical-correlation-analysis.html#cb41-8" tabindex="-1"></a>objA <span class="ot">&lt;-</span> <span class="fu">eigen</span>(A)</span>
<span id="cb41-9"><a href="canonical-correlation-analysis.html#cb41-9" tabindex="-1"></a>ea <span class="ot">&lt;-</span> objA<span class="sc">$</span>vector</span>
<span id="cb41-10"><a href="canonical-correlation-analysis.html#cb41-10" tabindex="-1"></a>(rsuqre <span class="ot">&lt;-</span> objA<span class="sc">$</span>values)</span></code></pre></div>
<pre><code>## [1] 0.1993055329 0.0235189905 0.0005064066</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="canonical-correlation-analysis.html#cb43-1" tabindex="-1"></a>(r1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(objA<span class="sc">$</span>values)) <span class="co">#the correlation, the same as r</span></span></code></pre></div>
<pre><code>## [1] 0.44643648 0.15335902 0.02250348</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="canonical-correlation-analysis.html#cb45-1" tabindex="-1"></a>ca <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">t</span>(ea)<span class="sc">%*%</span>s11<span class="sc">%*%</span>ea) <span class="co">#figure out the normalizing constants, var(u1)=1</span></span>
<span id="cb45-2"><a href="canonical-correlation-analysis.html#cb45-2" tabindex="-1"></a>(a1 <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">t</span>(ea)<span class="sc">/</span><span class="fu">sqrt</span>(ca)))<span class="co">#normally, make the one with the largest magnitude positive</span></span></code></pre></div>
<pre><code>##            [,1]       [,2]       [,3]
## [1,] -0.8379311  0.5134098 -0.3328964
## [2,]  0.1670182  0.5941199  0.8502290
## [3,] -0.4281181 -0.9034217  0.3747775</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="canonical-correlation-analysis.html#cb47-1" tabindex="-1"></a>(a1 <span class="ot">&lt;-</span> <span class="sc">-</span>a1) <span class="co"># the same as a</span></span></code></pre></div>
<pre><code>##            [,1]       [,2]       [,3]
## [1,]  0.8379311 -0.5134098  0.3328964
## [2,] -0.1670182 -0.5941199 -0.8502290
## [3,]  0.4281181  0.9034217 -0.3747775</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="canonical-correlation-analysis.html#cb49-1" tabindex="-1"></a>(b01 <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">t</span>(<span class="fu">solve</span>(s22)<span class="sc">%*%</span>s21<span class="sc">%*%</span>a1)<span class="sc">/</span>r1)) <span class="co">#if want p variates</span></span></code></pre></div>
<pre><code>##                [,1]        [,2]       [,3]
## read     0.44500741  0.01609314 -0.8924138
## write    0.53581915  0.87941356  0.9349929
## math     0.18265622  0.02782487 -0.8268251
## science -0.03686176 -1.20559459  0.8589501</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="canonical-correlation-analysis.html#cb51-1" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">solve</span>(s22)<span class="sc">%*%</span>s21<span class="sc">%*%</span><span class="fu">solve</span>(s11)<span class="sc">%*%</span>s12</span>
<span id="cb51-2"><a href="canonical-correlation-analysis.html#cb51-2" tabindex="-1"></a>objB <span class="ot">&lt;-</span> <span class="fu">eigen</span>(B)</span>
<span id="cb51-3"><a href="canonical-correlation-analysis.html#cb51-3" tabindex="-1"></a>eb <span class="ot">&lt;-</span> objB<span class="sc">$</span>vector</span>
<span id="cb51-4"><a href="canonical-correlation-analysis.html#cb51-4" tabindex="-1"></a>cb <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">t</span>(eb)<span class="sc">%*%</span>s22<span class="sc">%*%</span>eb) <span class="co">#figure out the normalizing constants, var(v1)=1</span></span>
<span id="cb51-5"><a href="canonical-correlation-analysis.html#cb51-5" tabindex="-1"></a>(b1 <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">t</span>(eb)<span class="sc">/</span><span class="fu">sqrt</span>(cb))) <span class="co"># the same as b</span></span></code></pre></div>
<pre><code>##             [,1]        [,2]       [,3]         [,4]
## [1,]  0.44500741  0.01609314  0.8924138  1.226181509
## [2,]  0.53581915  0.87941356 -0.9349929 -0.003555487
## [3,]  0.18265622  0.02782487  0.8268251 -1.263818759
## [4,] -0.03686176 -1.20559459 -0.8589501 -0.094063966</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="canonical-correlation-analysis.html#cb53-1" tabindex="-1"></a>(rxu1 <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(a1)))</span></code></pre></div>
<pre><code>##            [,1]       [,2]        [,3]
## [1,] 0.91428518 -0.3936580  0.09547756
## [2,] 0.09996773 -0.4213083 -0.90139104
## [3,] 0.58532551  0.6061228 -0.53852502</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="canonical-correlation-analysis.html#cb55-1" tabindex="-1"></a>(ryv1 <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(b1)))</span></code></pre></div>
<pre><code>##           [,1]       [,2]       [,3]        [,4]
## [1,] 0.8804322 -0.2449104  0.2730572  0.30049590
## [2,] 0.9101273  0.2209695 -0.3397966 -0.08590112
## [3,] 0.7999910 -0.1879332  0.2835709 -0.49424992
## [4,] 0.6941031 -0.6758881 -0.2376728 -0.07005600</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="canonical-correlation-analysis.html#cb57-1" tabindex="-1"></a>(rxv1 <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(a))<span class="sc">%*%</span><span class="fu">diag</span>(<span class="fu">sqrt</span>(objA<span class="sc">$</span>values)))</span></code></pre></div>
<pre><code>##            [,1]        [,2]         [,3]
## [1,] 0.27358831 -0.04046547  0.001440148
## [2,] 0.03148649 -0.04558417 -0.014310922
## [3,] 0.08955883  0.03185820 -0.004153430</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="canonical-correlation-analysis.html#cb59-1" tabindex="-1"></a>(ryu1 <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(b))<span class="sc">%*%</span><span class="fu">diag</span>(<span class="fu">sqrt</span>(objB<span class="sc">$</span>values)))</span></code></pre></div>
<pre><code>##          [,1]       [,2]        [,3]          [,4]
## [1,] 3.971049 -0.3794601  0.06208017  1.122235e-08
## [2,] 3.951995  0.3296068 -0.07437436 -3.088511e-09
## [3,] 3.362428 -0.2713445  0.06007856 -1.720087e-08
## [4,] 3.007682 -1.0060798 -0.05191315 -2.513560e-09</code></pre>
<p>We can also use the built-in function to obtain matrices of correlations between the original variables and canonical variates.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="canonical-correlation-analysis.html#cb61-1" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">cc</span>(x1,x2)</span>
<span id="cb61-2"><a href="canonical-correlation-analysis.html#cb61-2" tabindex="-1"></a>temp <span class="ot">&lt;-</span> m1<span class="sc">$</span>scores</span>
<span id="cb61-3"><a href="canonical-correlation-analysis.html#cb61-3" tabindex="-1"></a><span class="fu">names</span>(temp)</span></code></pre></div>
<pre><code>## [1] &quot;xscores&quot;        &quot;yscores&quot;        &quot;corr.X.xscores&quot; &quot;corr.Y.xscores&quot;
## [5] &quot;corr.X.yscores&quot; &quot;corr.Y.yscores&quot;</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="canonical-correlation-analysis.html#cb63-1" tabindex="-1"></a>(xu <span class="ot">&lt;-</span> temp<span class="sc">$</span>corr.X.xscores) <span class="co"># the same as rxu1 with correlation matrix</span></span></code></pre></div>
<pre><code>##                         [,1]       [,2]        [,3]
## locus_of_control -0.91428518  0.3936580  0.09547756
## self_concept     -0.09996773  0.4213083 -0.90139104
## motivation       -0.58532551 -0.6061228 -0.53852502</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="canonical-correlation-analysis.html#cb65-1" tabindex="-1"></a>(yv <span class="ot">&lt;-</span> temp<span class="sc">$</span>corr.Y.yscores) <span class="co"># the same as ryv1 with correlation matrix</span></span></code></pre></div>
<pre><code>##               [,1]       [,2]       [,3]
## read    -0.8804322  0.2449104 -0.2730572
## write   -0.9101273 -0.2209695  0.3397966
## math    -0.7999910  0.1879332 -0.2835709
## science -0.6941031  0.6758881  0.2376728</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="canonical-correlation-analysis.html#cb67-1" tabindex="-1"></a>xv <span class="ot">&lt;-</span> temp<span class="sc">$</span>corr.X.yscores <span class="co"># the same as rxv1 with correlation matrix</span></span>
<span id="cb67-2"><a href="canonical-correlation-analysis.html#cb67-2" tabindex="-1"></a>yu <span class="ot">&lt;-</span> temp<span class="sc">$</span>corr.Y.xscores <span class="co"># the same as ryu1 with correlation matrix</span></span>
<span id="cb67-3"><a href="canonical-correlation-analysis.html#cb67-3" tabindex="-1"></a></span>
<span id="cb67-4"><a href="canonical-correlation-analysis.html#cb67-4" tabindex="-1"></a><span class="co">#or</span></span>
<span id="cb67-5"><a href="canonical-correlation-analysis.html#cb67-5" tabindex="-1"></a>ccmat <span class="ot">&lt;-</span> <span class="fu">comput</span>(x1,x2,m1)</span>
<span id="cb67-6"><a href="canonical-correlation-analysis.html#cb67-6" tabindex="-1"></a><span class="fu">names</span>(ccmat)</span></code></pre></div>
<pre><code>## [1] &quot;xscores&quot;        &quot;yscores&quot;        &quot;corr.X.xscores&quot; &quot;corr.Y.xscores&quot;
## [5] &quot;corr.X.yscores&quot; &quot;corr.Y.yscores&quot;</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="canonical-correlation-analysis.html#cb69-1" tabindex="-1"></a>ccmat[<span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>] <span class="co"># the same as xu, yu, xv, and yv in order</span></span></code></pre></div>
<pre><code>## $corr.X.xscores
##                         [,1]       [,2]        [,3]
## locus_of_control -0.91428518  0.3936580  0.09547756
## self_concept     -0.09996773  0.4213083 -0.90139104
## motivation       -0.58532551 -0.6061228 -0.53852502
## 
## $corr.Y.xscores
##               [,1]        [,2]         [,3]
## read    -0.3930571  0.03755922 -0.006144737
## write   -0.4063141 -0.03388766  0.007646605
## math    -0.3571452  0.02882125 -0.006381333
## science -0.3098729  0.10365354  0.005348465
## 
## $corr.X.yscores
##                         [,1]        [,2]         [,3]
## locus_of_control -0.40817026  0.06037101  0.002148577
## self_concept     -0.04462924  0.06461142 -0.020284434
## motivation       -0.26131066 -0.09295440 -0.012118686
## 
## $corr.Y.yscores
##               [,1]       [,2]       [,3]
## read    -0.8804322  0.2449104 -0.2730572
## write   -0.9101273 -0.2209695  0.3397966
## math    -0.7999910  0.1879332 -0.2835709
## science -0.6941031  0.6758881  0.2376728</code></pre>
</div>
<div id="testing-mathbfsigma_120" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Testing <span class="math inline">\(\mathbf{\Sigma}_{12}=0\)</span><a href="canonical-correlation-analysis.html#testing-mathbfsigma_120" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If <span class="math inline">\(\mathbf{\Sigma}_{12}=0\)</span>, all canonical correlations must be 0; there is no point in conducting a canonical correlation analysis. By the result of a likelihood ratio test, reject <span class="math inline">\(H_0: \mathbf{\Sigma}_{12}=0 (\rho_1=\rho_2=\cdots=\rho_p=0)\)</span> at the significance level <span class="math inline">\(\alpha\)</span> if <span class="math inline">\(-\left(n-1-\frac{p+q+1}{2}\right)\ln(\prod_{i=1}^p(1-\hat \rho_i^2))&gt;\chi_{pq}^2(\alpha)\)</span> where <span class="math inline">\(\hat \rho_1^2\ge \hat \rho_2^2\ge \cdots \ge \hat \rho_p^2\)</span> are the eigenvalues of the matrix <span class="math inline">\(\mathbf{\Sigma}_{11}^{-1}\mathbf{\Sigma}_{12}\mathbf{\Sigma}_{22}^{-1}\mathbf{\Sigma}_{21}\)</span>. We can conduct a sequence of hypotheses to determine the number of canonical variates pairs to summarize the data:
<span class="math display">\[\begin{align*}
H_0^{(k)}&amp;:\rho_1 \ne 0, \rho_2\ne 0, \cdots, \rho_k \ne 0, \rho_{k+1}=\cdots=\rho_p=0\\
H_a^{(k)}&amp;:\rho_i\ne 0 \mbox{ for $i\ge k+1$}
\end{align*}\]</span>
Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(-\left(n-1-\frac{p+q+1}{2}\right)\ln(\prod_{i=k+1}^p(1-\hat \rho_i^2))&gt;\chi_{(p-k)(q-k)}^2(\alpha)\)</span>.</p>
<p><span class="math inline">\(\textbf{Example}\)</span>: Canonical Correlation Analysis (continued)</p>
<ol style="list-style-type: decimal">
<li>How much data variation can be explained by the first canonical variates?</li>
<li>At the 5% significance level, test whether the canonical relations are significant.</li>
<li>How many pairs of canonical variates provide a good summary of the relations between the two sets of variables?</li>
</ol>
<p>We have done Part (a) in the previous section. Based on the computer output, <span class="math inline">\(u_1\)</span> accounts for 39.62% of the variation in <span class="math inline">\(\mathbf{X}\)</span> and <span class="math inline">\(v_1\)</span> accounts for 68.13% of the variation in <span class="math inline">\(\mathbf{Y}\)</span>. <span class="math inline">\(v_1\)</span> has a better representation of the academic variables. Here is another way to obtain the percentage.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="canonical-correlation-analysis.html#cb71-1" tabindex="-1"></a>s11 <span class="ot">&lt;-</span> <span class="fu">cov</span>(x1)</span>
<span id="cb71-2"><a href="canonical-correlation-analysis.html#cb71-2" tabindex="-1"></a>s22 <span class="ot">&lt;-</span> <span class="fu">cov</span>(x2)</span>
<span id="cb71-3"><a href="canonical-correlation-analysis.html#cb71-3" tabindex="-1"></a>s12 <span class="ot">&lt;-</span> <span class="fu">cov</span>(x1,x2)</span>
<span id="cb71-4"><a href="canonical-correlation-analysis.html#cb71-4" tabindex="-1"></a>s21 <span class="ot">&lt;-</span> <span class="fu">t</span>(s12)</span>
<span id="cb71-5"><a href="canonical-correlation-analysis.html#cb71-5" tabindex="-1"></a></span>
<span id="cb71-6"><a href="canonical-correlation-analysis.html#cb71-6" tabindex="-1"></a>(<span class="at">pmatu=</span><span class="fu">t</span>(<span class="fu">t</span>(a)<span class="sc">%*%</span>s11))</span></code></pre></div>
<pre><code>##                        [,1]       [,2]        [,3]
## locus_of_control 0.61282695 -0.2638611  0.06399669
## self_concept     0.07052849 -0.2972383 -0.63594265
## motivation       0.20060823  0.2077361 -0.18456833</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="canonical-correlation-analysis.html#cb73-1" tabindex="-1"></a>(<span class="at">pmatv=</span><span class="fu">t</span>(<span class="fu">t</span>(b)<span class="sc">%*%</span>s22))</span></code></pre></div>
<pre><code>##             [,1]      [,2]      [,3]       [,4]
## read    8.894992 -2.474325  2.758692  3.0359049
## write   8.852313  2.149250 -3.305016 -0.8355134
## math    7.531705 -1.769342  2.669746 -4.6532327
## science 6.737088 -6.560291 -2.306895 -0.6799760</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="canonical-correlation-analysis.html#cb75-1" tabindex="-1"></a><span class="fu">sum</span>(pmatu[,<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">sum</span>(pmatu<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.3952843</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="canonical-correlation-analysis.html#cb77-1" tabindex="-1"></a><span class="fu">sum</span>(pmatv[,<span class="dv">1</span>]<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">sum</span>(pmatv<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.6840175</code></pre>
<p>Here is the R code for Part (b).</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="canonical-correlation-analysis.html#cb79-1" tabindex="-1"></a>data0 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/mmreg.csv&quot;</span>)</span>
<span id="cb79-2"><a href="canonical-correlation-analysis.html#cb79-2" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> data0[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb79-3"><a href="canonical-correlation-analysis.html#cb79-3" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> data0[,<span class="dv">4</span><span class="sc">:</span><span class="dv">7</span>]</span>
<span id="cb79-4"><a href="canonical-correlation-analysis.html#cb79-4" tabindex="-1"></a></span>
<span id="cb79-5"><a href="canonical-correlation-analysis.html#cb79-5" tabindex="-1"></a><span class="co">#work on the correlation matrices</span></span>
<span id="cb79-6"><a href="canonical-correlation-analysis.html#cb79-6" tabindex="-1"></a>s11 <span class="ot">&lt;-</span> <span class="fu">cor</span>(x1)</span>
<span id="cb79-7"><a href="canonical-correlation-analysis.html#cb79-7" tabindex="-1"></a>s22 <span class="ot">&lt;-</span> <span class="fu">cor</span>(x2)</span>
<span id="cb79-8"><a href="canonical-correlation-analysis.html#cb79-8" tabindex="-1"></a>s12 <span class="ot">&lt;-</span> <span class="fu">cor</span>(x1,x2)</span>
<span id="cb79-9"><a href="canonical-correlation-analysis.html#cb79-9" tabindex="-1"></a>s21 <span class="ot">&lt;-</span> <span class="fu">t</span>(s12)</span>
<span id="cb79-10"><a href="canonical-correlation-analysis.html#cb79-10" tabindex="-1"></a></span>
<span id="cb79-11"><a href="canonical-correlation-analysis.html#cb79-11" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">solve</span>(s11)<span class="sc">%*%</span>s12<span class="sc">%*%</span><span class="fu">solve</span>(s22)<span class="sc">%*%</span>s21</span>
<span id="cb79-12"><a href="canonical-correlation-analysis.html#cb79-12" tabindex="-1"></a></span>
<span id="cb79-13"><a href="canonical-correlation-analysis.html#cb79-13" tabindex="-1"></a>objA <span class="ot">&lt;-</span> <span class="fu">eigen</span>(A)</span>
<span id="cb79-14"><a href="canonical-correlation-analysis.html#cb79-14" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb79-15"><a href="canonical-correlation-analysis.html#cb79-15" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(x1)</span>
<span id="cb79-16"><a href="canonical-correlation-analysis.html#cb79-16" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ncol</span>(x1)</span>
<span id="cb79-17"><a href="canonical-correlation-analysis.html#cb79-17" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">ncol</span>(x2)</span>
<span id="cb79-18"><a href="canonical-correlation-analysis.html#cb79-18" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">min</span>(p,q)</span>
<span id="cb79-19"><a href="canonical-correlation-analysis.html#cb79-19" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,k)</span>
<span id="cb79-20"><a href="canonical-correlation-analysis.html#cb79-20" tabindex="-1"></a>qvec <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,k)</span>
<span id="cb79-21"><a href="canonical-correlation-analysis.html#cb79-21" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>k){</span>
<span id="cb79-22"><a href="canonical-correlation-analysis.html#cb79-22" tabindex="-1"></a>test[i] <span class="ot">&lt;-</span> <span class="sc">-</span>(n<span class="dv">-1</span><span class="sc">-</span>(p<span class="sc">+</span>q<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span><span class="dv">2</span>)<span class="sc">*</span><span class="fu">log</span>(<span class="fu">prod</span>(<span class="dv">1</span><span class="sc">-</span>objA<span class="sc">$</span>values[i<span class="sc">:</span>k]))</span>
<span id="cb79-23"><a href="canonical-correlation-analysis.html#cb79-23" tabindex="-1"></a>qvec[i] <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(alpha,(p<span class="sc">-</span>i<span class="sc">+</span><span class="dv">1</span>)<span class="sc">*</span>(q<span class="sc">-</span>i<span class="sc">+</span><span class="dv">1</span>),<span class="at">lower.tail =</span> F)</span>
<span id="cb79-24"><a href="canonical-correlation-analysis.html#cb79-24" tabindex="-1"></a>}</span>
<span id="cb79-25"><a href="canonical-correlation-analysis.html#cb79-25" tabindex="-1"></a><span class="fu">cbind</span>(test,qvec)</span></code></pre></div>
<pre><code>##             test      qvec
## [1,] 146.7165014 21.026070
## [2,]  14.4623742 12.591587
## [3,]   0.3013882  5.991465</code></pre>
<p>The steps for the test are as follows.</p>
<ol style="list-style-type: decimal">
<li>Hypotheses.<span class="math inline">\(H_0: \rho_1=\rho_2=\rho_3=0\)</span> v.s. $H_a: $.</li>
<li>Significance level <span class="math inline">\(\alpha=0.05\)</span></li>
<li>Test statistic.
<span class="math display">\[
-\left(n-1-\frac{p+q+1}{2}\right)\ln(\prod_{i=1}^p(1-\hat \rho_i^2))=146.7165
\]</span></li>
<li>Decision: since <span class="math inline">\(146.7165&gt;\chi_{(p=3)(q=4)}^2(0.05)=\chi_{12}^2(0.05)=21.026\)</span>, we reject <span class="math inline">\(H_0\)</span>.</li>
<li>Conclusions: at the 5% significance level, we have sufficient evidence that the at least one canonical correlation is not zero.</li>
</ol>
<p>Based on a sequence of hypotheses, we reject the first two and can not reject the third one. As a result, we might need two pairs of canonical variates to provide a good summary of the relations between the two sets of variables.</p>
<p>We can conduct the sequence of tests using built-in function to determine the number of canonical variates pairs.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="canonical-correlation-analysis.html#cb81-1" tabindex="-1"></a><span class="co">#determine number of pairs</span></span>
<span id="cb81-2"><a href="canonical-correlation-analysis.html#cb81-2" tabindex="-1"></a><span class="fu">library</span>(CCP)</span>
<span id="cb81-3"><a href="canonical-correlation-analysis.html#cb81-3" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(x1)</span>
<span id="cb81-4"><a href="canonical-correlation-analysis.html#cb81-4" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ncol</span>(x1)</span>
<span id="cb81-5"><a href="canonical-correlation-analysis.html#cb81-5" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">ncol</span>(x2)</span>
<span id="cb81-6"><a href="canonical-correlation-analysis.html#cb81-6" tabindex="-1"></a><span class="fu">p.asym</span>(m1<span class="sc">$</span>cor,n,p,q,<span class="at">tstat =</span> <span class="st">&quot;Wilks&quot;</span>)</span></code></pre></div>
<pre><code>## Wilks&#39; Lambda, using F-approximation (Rao&#39;s F):
##               stat     approx df1      df2   p.value
## 1 to 3:  0.7814670 12.7735403  12 1569.222 0.0000000
## 2 to 3:  0.9759865  2.4210265   6 1188.000 0.0248771
## 3 to 3:  0.9994936  0.1507323   2  595.000 0.8601108</code></pre>
</div>
<div id="revisit-learning-outcomes-2" class="section level2 unnumbered hasAnchor">
<h2>Revisit Learning Outcomes<a href="canonical-correlation-analysis.html#revisit-learning-outcomes-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>After finishing this chapter, students should be able to</p>
<ul>
<li>Understand the objective of canonical correlation analysis.</li>
<li>Prove important results related to canonical correlation analysis.</li>
<li>Conduct a canonical correlation analysis in R.</li>
<li>Interpret the computer output of a canonical correlation analysis.</li>
<li>Conduct a hypothesis test to test whether the canonical relations are significant.</li>
<li>Determine the proper number of canonical variates pairs.</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="clustering-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multidimensional-scaling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
